### EKAT TESTIT

### Palvelimen juuri
GET http://localhost:3000

### morotesti
GET http://localhost:3000/moro

### morotesti POST
POST http://localhost:3000/api/moro
content-type: application/json

{
    "sender": "Vanilla",
    "message": "testitervehdys"
}


### ITEMS

### get all items
GET http://localhost:3000/api/items

### get item by ID
GET http://localhost:3000/api/items/3


### post items
POST http://localhost:3000/api/items
content-type: application/json

{
    "name": "Sitruuna"
}


### CAT

### Get cat

GET http://localhost:3000/api/cat?number=10

### Get wrong

GET http://localhost:3000/api/cat?number=5


### USERS

### Get users
GET http://127.0.0.1:3000/api/users

### Get user by ID
GET http://127.0.0.1:3000/api/users/2

### Post user
POST http://127.0.0.1:3000/api/users
content-type: application/json

{
    "username": "Sitruuna",
    "password": "Peruna",
    "email": "Sitruuna.Peruna@mailmail.com"
}

### Post login
POST http://127.0.0.1:3000/api/users/login
content-type: application/json

{
    "username": "johndoe",
    "password": "password1"
}